name: Build and push

on: [push]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up docker image
        id: setup
        run: |
          if [[ $GITHUB_REF =~ ^refs/tags/ ]]; then
            TAG=$(echo ${GITHUB_REF##*/})
          else
            TAG=$(echo ${GITHUB_SHA::7})
          fi
          IMAGE=${{ secrets.DOCKERHUB_REPOSITORY }}
          echo "{tagged_image}={${IMAGE}:${TAG}}" >> "$GITHUB_ENV"
          echo "{tag}={${TAG}}" >> "$GITHUB_ENV"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ${{ steps.setup.outputs.tagged_image }}
